// Studio Rate Card seeds (faithful to the reference App: RC_UNITS / RC_CATS_DEFAULT / RC_D).
export const RC_UNITS = [
  { id: "sqft", l: "/sqft" }, { id: "truss_sqft", l: "/truss sqft" }, { id: "rft", l: "/RFT" },
  { id: "pc", l: "/pc" }, { id: "setup", l: "/setup" }, { id: "trip", l: "/trip" },
  { id: "event", l: "/event" }, { id: "string", l: "/string" }, { id: "included", l: "Included" }, { id: "multiplier", l: "× mult" },
];

export const RC_CATS_DEFAULT = [
  { id: "truss", l: "Truss & Structure", icon: "🏗️", c: "#6366F1", d: "Box truss, Single U — skeleton for all zones" },
  { id: "masking", l: "Wall Masking", icon: "🧱", c: "#8B5CF6", d: "Fabric, panel, prints on truss walls" },
  { id: "platform", l: "Platform & Carpet", icon: "🪜", c: "#A78BFA", d: "Raised platforms, floor carpeting" },
  { id: "ceiling", l: "Ceiling", icon: "☁️", c: "#818CF8", d: "Normal drapes (included), special patterns, prefab, custom" },
  { id: "florals", l: "Florals", icon: "🌸", c: "#EC4899", d: "Universal rates — same price in every zone" },
  { id: "lighting", l: "Lighting", icon: "💡", c: "#F59E0B", d: "Chandeliers, fairy lights, floods, LEDs, spots" },
  { id: "furniture", l: "Furniture", icon: "🛋️", c: "#10B981", d: "Sofas, chairs, tables — inhouse + outsource" },
  { id: "arches", l: "Arches & Props", icon: "🚪", c: "#F97316", d: "Entry arches, props, welcome boards, neons" },
  { id: "wroughtiron", l: "Wrought Iron", icon: "⚙️", c: "#78716C", d: "Wrought iron setups — priced per piece or per setup" },
  { id: "glass", l: "Glass Panels", icon: "💎", c: "#06B6D4", d: "2D & 3D glass panels — per sqft pricing" },
  { id: "fixed", l: "Fixed Costs", icon: "🔧", c: "#6B7280", d: "Genset, outstation multiplier" },
];

export const RC_D = [
  { id: "T01", cat: "truss", sub: "Box Truss", name: "Box Truss", unit: "sqft", calcLogic: "top2_of_LWH", inhouseMode: "flat", inhouseFlat: 50, outEnabled: false, notes: "Top 2 of L×W×H. Includes normal ceiling drapes & fabric." },
  { id: "T02", cat: "truss", sub: "Single U Truss", name: "Single U Truss", unit: "sqft", calcLogic: "WxH", inhouseMode: "flat", inhouseFlat: 30, outEnabled: false, notes: "W × H. For entry gates, arches, backdrops." },
  { id: "M01", cat: "masking", sub: "Fabric", name: "Fabric Masking", unit: "sqft", inhouseMode: "flat", inhouseFlat: 20, outEnabled: false, notes: "Plain fabric. Default 1 side." },
  { id: "M02", cat: "masking", sub: "Acrylic Panel", name: "Acrylic Panel", unit: "sqft", inhouseMode: "flat", inhouseFlat: 100, outEnabled: false, notes: "Premium panels." },
  { id: "M03", cat: "masking", sub: "Flex Print", name: "Flex Print", unit: "sqft", inhouseMode: "flat", inhouseFlat: 45, outEnabled: false, notes: "Printed graphics." },
  { id: "M04", cat: "masking", sub: "Vinyl Print", name: "Vinyl Print", unit: "sqft", inhouseMode: "flat", inhouseFlat: 90, outEnabled: false, notes: "Premium quality print." },
  { id: "P01", cat: "platform", sub: "Platform", name: "Platform (4 inch raise)", unit: "sqft", inhouseMode: "flat", inhouseFlat: 30, outEnabled: false, notes: "Low platform." },
  { id: "P02", cat: "platform", sub: "Platform", name: "Platform (1ft-3ft)", unit: "sqft", inhouseMode: "flat", inhouseFlat: 45, outEnabled: false, notes: "All heights 1ft to 3ft." },
  { id: "P03", cat: "platform", sub: "Carpet", name: "Carpet (New)", unit: "sqft", inhouseMode: "flat", inhouseFlat: 15, outEnabled: false, notes: "Fresh new carpet." },
  { id: "P04", cat: "platform", sub: "Carpet", name: "Carpet (Old)", unit: "sqft", inhouseMode: "flat", inhouseFlat: 7, outEnabled: false, notes: "Reused — budget." },
  { id: "C01", cat: "ceiling", sub: "Drapes", name: "Normal Drapes", unit: "included", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "Included in truss." },
  { id: "C02", cat: "ceiling", sub: "Special Pattern", name: "Star Pattern Ceiling", unit: "setup", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set price — labour intensive." },
  { id: "C03", cat: "ceiling", sub: "Special Pattern", name: "Layered Drape Ceiling", unit: "setup", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set price." },
  { id: "C04", cat: "ceiling", sub: "Prefab", name: "Prefab Ceiling (IMS)", unit: "pc", inhouseMode: "smb", inhouseS: 0, inhouseM: 0, inhouseB: 0, outEnabled: false, notes: "⚠️ Set prices — from godown." },
  { id: "C05", cat: "ceiling", sub: "Custom", name: "Custom Fabricated Ceiling", unit: "setup", inhouseMode: "flat", inhouseFlat: 0, outEnabled: true, outS: 0, outM: 0, outB: 0, notes: "⚠️ Outsourced fabrication." },
  { id: "F01", cat: "florals", sub: "Flower Garden", name: "Flower Garden", unit: "rft", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate — per running ft." },
  { id: "F02", cat: "florals", sub: "Flower Garden", name: "Flower Garden (Premium)", unit: "rft", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "F03", cat: "florals", sub: "Reet / Garland", name: "Floral Reet Standard", unit: "rft", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "F04", cat: "florals", sub: "Reet / Garland", name: "Floral Reet Heavy", unit: "rft", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "F05", cat: "florals", sub: "Flower Pot", name: "Flower Pot (Small)", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "F06", cat: "florals", sub: "Flower Pot", name: "Flower Pot (Large)", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "F07", cat: "florals", sub: "Table Floral", name: "Coffee Table Floral", unit: "pc", inhouseMode: "flat", inhouseFlat: 1500, outEnabled: false, notes: "Confirmed." },
  { id: "F08", cat: "florals", sub: "Table Floral", name: "Cocktail Table Floral", unit: "pc", inhouseMode: "flat", inhouseFlat: 800, outEnabled: false, notes: "Confirmed." },
  { id: "F09", cat: "florals", sub: "Centerpiece", name: "Centerpiece", unit: "pc", inhouseMode: "flat", inhouseFlat: 2500, outEnabled: false, notes: "Confirmed." },
  { id: "F10", cat: "florals", sub: "Table Arrangement", name: "Round Table Arrangement", unit: "pc", inhouseMode: "flat", inhouseFlat: 1500, outEnabled: false, notes: "Confirmed." },
  { id: "F11", cat: "florals", sub: "Stage Floral", name: "Couple Couch + Flower Garden", unit: "pc", inhouseMode: "flat", inhouseFlat: 15000, outEnabled: false, notes: "Confirmed. Qty 1." },
  { id: "F12", cat: "florals", sub: "Console Floral", name: "Console Table Floral", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "L01", cat: "lighting", sub: "Chandelier", name: "Chandelier", unit: "pc", inhouseMode: "smb", inhouseS: 0, inhouseM: 3500, inhouseB: 0, outEnabled: true, outS: 0, outM: 0, outB: 0, notes: "Gold ₹3,500 confirmed. Set Small & Big." },
  { id: "L02", cat: "lighting", sub: "Fairy Lights", name: "Fairy Lights", unit: "string", inhouseMode: "flat", inhouseFlat: 30, outEnabled: false, notes: "Confirmed." },
  { id: "L03", cat: "lighting", sub: "Flood Light", name: "Flood Light", unit: "pc", inhouseMode: "flat", inhouseFlat: 250, outEnabled: false, notes: "Confirmed." },
  { id: "L04", cat: "lighting", sub: "LED Light", name: "LED Light", unit: "pc", inhouseMode: "flat", inhouseFlat: 250, outEnabled: false, notes: "Confirmed." },
  { id: "L05", cat: "lighting", sub: "Spot / Uplight", name: "Spot / Uplight", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "FU01", cat: "furniture", sub: "Sofa", name: "Sofa (2-Seater)", unit: "pc", inhouseMode: "flat", inhouseFlat: 2500, outEnabled: true, outS: 0, outM: 0, outB: 0, notes: "Inhouse confirmed." },
  { id: "FU02", cat: "furniture", sub: "Coffee Table", name: "Coffee Table", unit: "pc", inhouseMode: "flat", inhouseFlat: 1200, outEnabled: true, outS: 0, outM: 0, outB: 0, notes: "Confirmed." },
  { id: "FU03", cat: "furniture", sub: "Side Box", name: "Side Box", unit: "pc", inhouseMode: "flat", inhouseFlat: 1000, outEnabled: false, notes: "Confirmed." },
  { id: "FU04", cat: "furniture", sub: "Chair", name: "Chair (Standard)", unit: "pc", inhouseMode: "flat", inhouseFlat: 300, outEnabled: true, outS: 0, outM: 0, outB: 0, notes: "Confirmed." },
  { id: "FU05", cat: "furniture", sub: "Round Table", name: "Round Table", unit: "pc", inhouseMode: "flat", inhouseFlat: 400, outEnabled: false, notes: "Confirmed." },
  { id: "FU06", cat: "furniture", sub: "Cocktail Table", name: "Cocktail Table", unit: "pc", inhouseMode: "flat", inhouseFlat: 1000, outEnabled: false, notes: "Confirmed." },
  { id: "FU07", cat: "furniture", sub: "Console Table", name: "Console Table", unit: "pc", inhouseMode: "flat", inhouseFlat: 6000, outEnabled: false, notes: "Confirmed." },
  { id: "A01", cat: "arches", sub: "Arch", name: "Entry Arch (Standard)", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate. Needs truss." },
  { id: "A02", cat: "arches", sub: "Arch", name: "Royal Arch (Large)", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "A03", cat: "arches", sub: "Props", name: "Props (Standard)", unit: "pc", inhouseMode: "flat", inhouseFlat: 3500, outEnabled: true, outS: 0, outM: 0, outB: 0, notes: "₹3,500 inhouse." },
  { id: "A04", cat: "arches", sub: "Welcome Board", name: "Welcome Board + Installation", unit: "pc", inhouseMode: "flat", inhouseFlat: 7000, outEnabled: false, notes: "Confirmed. Qty 1." },
  { id: "A05", cat: "arches", sub: "Photo Op", name: "Photo Op Setup", unit: "pc", inhouseMode: "flat", inhouseFlat: 40000, outEnabled: true, outS: 0, outM: 0, outB: 0, notes: "₹40K inhouse." },
  { id: "A06", cat: "arches", sub: "Neon Sign", name: "Neon Sign", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "X01", cat: "fixed", sub: "Genset", name: "Genset 125 KV", unit: "event", inhouseMode: "flat", inhouseFlat: 28000, outEnabled: false, notes: "Per event." },
  { id: "X02", cat: "fixed", sub: "Outstation", name: "Outstation Multiplier", unit: "multiplier", inhouseMode: "flat", inhouseFlat: 1.5, outEnabled: false, notes: "Multiplied on total." },
  { id: "WI01", cat: "wroughtiron", sub: "Gate", name: "Wrought Iron Gate", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate. Price varies by design." },
  { id: "WI02", cat: "wroughtiron", sub: "Panel", name: "Wrought Iron Panel", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "WI03", cat: "wroughtiron", sub: "Arch", name: "Wrought Iron Arch", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "WI04", cat: "wroughtiron", sub: "Mandap Frame", name: "Wrought Iron Mandap Frame", unit: "setup", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate per setup." },
  { id: "WI05", cat: "wroughtiron", sub: "Railing", name: "Wrought Iron Railing", unit: "rft", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate per running ft." },
  { id: "WI06", cat: "wroughtiron", sub: "Stage Frame", name: "Wrought Iron Stage Frame", unit: "setup", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate per setup." },
  { id: "WI07", cat: "wroughtiron", sub: "Photo Op", name: "Wrought Iron Photo Op Frame", unit: "pc", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
  { id: "GP01", cat: "glass", sub: "2D Panel", name: "Glass Panel 2D (Flat)", unit: "sqft", inhouseMode: "flat", inhouseFlat: 120, outEnabled: false, notes: "Flat glass panel. ₹120/sqft confirmed." },
  { id: "GP02", cat: "glass", sub: "3D Panel", name: "Glass Panel 3D (Built-out)", unit: "sqft", inhouseMode: "flat", inhouseFlat: 180, outEnabled: false, notes: "3D built-out glass. ₹180/sqft confirmed." },
  { id: "GP03", cat: "glass", sub: "Mirror Panel", name: "Mirror Panel", unit: "sqft", inhouseMode: "flat", inhouseFlat: 0, outEnabled: false, notes: "⚠️ Set rate." },
];
