// Shared IMS constants (non-inventory). Faithful to the reference app.
export const VENDOR_TYPES = ["Manpower Contractor", "Transport", "Inventory Supplier", "Printing", "Flower Supplier", "Rental", "Service"];
export const OVERHEAD_CATS = ["Godown Rent", "Fixed Staff Salaries", "Utilities", "Vehicle EMI/Maintenance", "Equipment Maintenance", "Subscriptions/Software", "Other"];

// Minimal default settings so finance math (buffer / min-profit) + date pricing work
// before the Settings phase populates the real settings table. Faithful to INIT_SETTINGS.
export const SETTINGS_DEFAULTS = {
  bufferPct: 5,
  minProfitPct: 30,
  datePricing: {
    lastMinuteDays: 10,
    categories: {
      heavy_saya: { label: "🔴 Heavy Saya", multiplier: 1.4, color: "red" },
      competition: { label: "🟡 Perfect Competition", multiplier: 1.0, color: "yellow" },
      non_saya: { label: "🟢 Non-Saya", multiplier: 0.75, color: "green" },
    },
    markedDates: {},
  },
  artificialColours: ["Red", "White", "Pastels", "Yellow/Orange", "Purple", "Greens", "Mixed/Other"],
  artificialKgToPieces: 200,
  mandiPriceMultipliers: { heavy_saya: 1.4, competition: 1.0, non_saya: 0.85 },
  flowerCategories: ["Rose", "Daisy", "Carnation", "Stock", "Lily & Orchid", "Gladiolus", "Anthurium", "Guldavari", "Marigold", "Mogra", "Tuberose", "Sunflower", "Ranunculus", "Filler & Green", "Palm & Leaf", "Patti (Leaves)", "Specialty", "Other"],
  mandiCatalogue: [
    { id: "F001", flowerCat: "Rose", name: "Rose Baby Pink", unit: "bundle", gattharSize: null, currentPrice: 550, priceHistory: [{ price: 500, date: "2026-02-19" }] },
    { id: "F002", flowerCat: "Rose", name: "Rose White", unit: "bundle", gattharSize: null, currentPrice: 300, priceHistory: [{ price: 300, date: "2026-02-23" }] },
    { id: "F003", flowerCat: "Rose", name: "Rose Rani Pink", unit: "bundle", gattharSize: null, currentPrice: 500, priceHistory: [{ price: 500, date: "2026-02-13" }] },
    { id: "F004", flowerCat: "Rose", name: "Rose Yellow (Pila Gulab)", unit: "bundle", gattharSize: null, currentPrice: 500, priceHistory: [{ price: 500, date: "2026-02-13" }] },
    { id: "F005", flowerCat: "Rose", name: "Rose Peach", unit: "bundle", gattharSize: null, currentPrice: 300, priceHistory: [{ price: 300, date: "2026-02-23" }] },
    { id: "F006", flowerCat: "Daisy", name: "Daisy White", unit: "bundle", gattharSize: null, currentPrice: 350, priceHistory: [{ price: 300, date: "2026-02-23" }, { price: 350, date: "2026-02-19" }] },
    { id: "F007", flowerCat: "Daisy", name: "Daisy Pink", unit: "bundle", gattharSize: null, currentPrice: 350, priceHistory: [{ price: 350, date: "2026-02-13" }] },
    { id: "F008", flowerCat: "Daisy", name: "Daisy Maroon", unit: "bundle", gattharSize: null, currentPrice: 350, priceHistory: [{ price: 350, date: "2026-02-13" }] },
    { id: "F009", flowerCat: "Daisy", name: "Daisy Green", unit: "bundle", gattharSize: null, currentPrice: 350, priceHistory: [{ price: 350, date: "2026-02-13" }] },
    { id: "F010", flowerCat: "Daisy", name: "Daisy Yellow", unit: "bundle", gattharSize: null, currentPrice: 350, priceHistory: [{ price: 350, date: "2026-02-13" }] },
    { id: "F011", flowerCat: "Daisy", name: "Daisy Peach", unit: "bundle", gattharSize: null, currentPrice: 300, priceHistory: [{ price: 300, date: "2026-02-23" }] },
    { id: "F012", flowerCat: "Daisy", name: "Green Button Daisy", unit: "bundle", gattharSize: null, currentPrice: 350, priceHistory: [{ price: 400, date: "2026-02-23" }, { price: 300, date: "2026-02-19" }] },
    { id: "F013", flowerCat: "Daisy", name: "Santini Daisy", unit: "bundle", gattharSize: null, currentPrice: 350, priceHistory: [{ price: 400, date: "2026-02-13" }, { price: 300, date: "2026-02-23" }] },
    { id: "F014", flowerCat: "Daisy", name: "Calcutta Button Daisy", unit: "bundle", gattharSize: null, currentPrice: 375, priceHistory: [{ price: 375, date: "2026-02-19" }] },
    { id: "F015", flowerCat: "Carnation", name: "Carnation White", unit: "bundle", gattharSize: null, currentPrice: 300, priceHistory: [{ price: 200, date: "2026-02-23" }, { price: 250, date: "2026-02-19" }] },
    { id: "F016", flowerCat: "Carnation", name: "Spray Carnation Baby Pink", unit: "bundle", gattharSize: null, currentPrice: 350, priceHistory: [{ price: 350, date: "2026-02-19" }] },
    { id: "F017", flowerCat: "Stock", name: "Stock Rani Pink", unit: "bundle", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-13" }] },
    { id: "F018", flowerCat: "Stock", name: "Stock Purple", unit: "bundle", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-13" }] },
    { id: "F019", flowerCat: "Stock", name: "Stock White", unit: "bundle", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 20, date: "2026-02-23" }, { price: 100, date: "2026-02-19" }] },
    { id: "F020", flowerCat: "Stock", name: "Stock Pink", unit: "bundle", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-19" }] },
    { id: "F021", flowerCat: "Stock", name: "Stock Peach", unit: "piece", gattharSize: null, currentPrice: 20, priceHistory: [{ price: 20, date: "2026-02-23" }] },
    { id: "F022", flowerCat: "Lily & Orchid", name: "Lily White", unit: "piece", gattharSize: null, currentPrice: 1000, priceHistory: [{ price: 1000, date: "2026-02-23" }, { price: 1200, date: "2026-02-19" }] },
    { id: "F023", flowerCat: "Lily & Orchid", name: "Orchid White", unit: "piece", gattharSize: null, currentPrice: 150, priceHistory: [{ price: 150, date: "2026-02-23" }] },
    { id: "F024", flowerCat: "Gladiolus", name: "Glad White", unit: "piece", gattharSize: null, currentPrice: 150, priceHistory: [{ price: 150, date: "2026-02-23" }] },
    { id: "F025", flowerCat: "Anthurium", name: "Anthurium White", unit: "piece", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-19" }, { price: 100, date: "2026-02-23" }] },
    { id: "F026", flowerCat: "Anthurium", name: "Anthurium Green", unit: "piece", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-23" }] },
    { id: "F027", flowerCat: "Guldavari", name: "Guldavari White", unit: "piece", gattharSize: null, currentPrice: 2000, priceHistory: [{ price: 2000, date: "2026-02-23" }] },
    { id: "F028", flowerCat: "Guldavari", name: "Guldavari Ladi", unit: "kg", gattharSize: null, currentPrice: 333, priceHistory: [{ price: 333, date: "2026-02-23" }] },
    { id: "F029", flowerCat: "Marigold", name: "Genda Loose Rupali", unit: "kg", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-13" }] },
    { id: "F030", flowerCat: "Marigold", name: "Genda Orange Loose", unit: "kg", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-13" }] },
    { id: "F031", flowerCat: "Mogra", name: "Mogra", unit: "gatthar", gattharSize: null, currentPrice: 3000, priceHistory: [{ price: 3000, date: "2026-02-23" }] },
    { id: "F032", flowerCat: "Tuberose", name: "Tuberose (Rajnigandha)", unit: "gatthar", gattharSize: 160, currentPrice: 580, priceHistory: [{ price: 580, date: "2026-02-23" }] },
    { id: "F033", flowerCat: "Filler & Green", name: "Gypso (Baby Breath)", unit: "bundle", gattharSize: null, currentPrice: 200, priceHistory: [{ price: 50, date: "2026-02-13" }, { price: 200, date: "2026-02-23" }, { price: 250, date: "2026-02-19" }] },
    { id: "F034", flowerCat: "Sunflower", name: "Sunflower", unit: "piece", gattharSize: null, currentPrice: 40, priceHistory: [{ price: 40, date: "2026-02-13" }] },
    { id: "F035", flowerCat: "Ranunculus", name: "Ranunculus Pink", unit: "piece", gattharSize: null, currentPrice: 150, priceHistory: [{ price: 150, date: "2026-02-13" }] },
    { id: "F036", flowerCat: "Ranunculus", name: "Ranunculus Green", unit: "piece", gattharSize: null, currentPrice: 150, priceHistory: [{ price: 150, date: "2026-02-13" }] },
    { id: "F037", flowerCat: "Filler & Green", name: "Amaranthus Red", unit: "bundle", gattharSize: null, currentPrice: 50, priceHistory: [{ price: 50, date: "2026-02-13" }] },
    { id: "F038", flowerCat: "Filler & Green", name: "Amaranthus Green", unit: "bundle", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 50, date: "2026-02-13" }, { price: 100, date: "2026-02-23" }] },
    { id: "F039", flowerCat: "Filler & Green", name: "Lemonium", unit: "bundle", gattharSize: null, currentPrice: 300, priceHistory: [{ price: 300, date: "2026-02-13" }] },
    { id: "F040", flowerCat: "Filler & Green", name: "Junado", unit: "bundle", gattharSize: null, currentPrice: 50, priceHistory: [{ price: 50, date: "2026-02-13" }, { price: 50, date: "2026-02-23" }] },
    { id: "F041", flowerCat: "Filler & Green", name: "Finger", unit: "bundle", gattharSize: null, currentPrice: 30, priceHistory: [{ price: 30, date: "2026-02-13" }, { price: 30, date: "2026-02-19" }] },
    { id: "F042", flowerCat: "Filler & Green", name: "Dandela", unit: "bundle", gattharSize: null, currentPrice: 50, priceHistory: [{ price: 50, date: "2026-02-23" }] },
    { id: "F043", flowerCat: "Filler & Green", name: "Black Berry", unit: "bundle", gattharSize: null, currentPrice: 250, priceHistory: [{ price: 250, date: "2026-02-23" }] },
    { id: "F044", flowerCat: "Filler & Green", name: "Dracaena Red", unit: "bundle", gattharSize: null, currentPrice: 20, priceHistory: [{ price: 20, date: "2026-02-13" }] },
    { id: "F045", flowerCat: "Palm & Leaf", name: "Fish Tail Palm", unit: "piece", gattharSize: null, currentPrice: 1000, priceHistory: [{ price: 1000, date: "2026-02-13" }, { price: 1000, date: "2026-02-19" }] },
    { id: "F046", flowerCat: "Palm & Leaf", name: "Ghoda Palm", unit: "piece", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-23" }] },
    { id: "F047", flowerCat: "Palm & Leaf", name: "Mocha", unit: "piece", gattharSize: null, currentPrice: 250, priceHistory: [{ price: 250, date: "2026-02-13" }, { price: 250, date: "2026-02-23" }] },
    { id: "F048", flowerCat: "Patti (Leaves)", name: "Delhi Patti", unit: "bundle", gattharSize: null, currentPrice: 200, priceHistory: [{ price: 100, date: "2026-02-13" }, { price: 200, date: "2026-02-19" }] },
    { id: "F049", flowerCat: "Patti (Leaves)", name: "English Green Patti", unit: "bundle", gattharSize: null, currentPrice: 3000, priceHistory: [{ price: 3000, date: "2026-02-23" }, { price: 3000, date: "2026-02-19" }] },
    { id: "F050", flowerCat: "Patti (Leaves)", name: "Morya Patti", unit: "bundle", gattharSize: null, currentPrice: 1000, priceHistory: [{ price: 167, date: "2026-02-23" }, { price: 1000, date: "2026-02-19" }] },
    { id: "F051", flowerCat: "Patti (Leaves)", name: "Gulab Patti (Rose Petals)", unit: "kg", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-13" }] },
    { id: "F052", flowerCat: "Patti (Leaves)", name: "Hinda Patti", unit: "kg", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-13" }] },
    { id: "F053", flowerCat: "Patti (Leaves)", name: "White Patti", unit: "kg", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-13" }] },
    { id: "F054", flowerCat: "Patti (Leaves)", name: "Salad Patti", unit: "bundle", gattharSize: null, currentPrice: 1000, priceHistory: [{ price: 1000, date: "2026-02-19" }] },
    { id: "F055", flowerCat: "Patti (Leaves)", name: "Golden Patti", unit: "kg", gattharSize: null, currentPrice: 100, priceHistory: [{ price: 100, date: "2026-02-19" }] },
    { id: "F056", flowerCat: "Patti (Leaves)", name: "Murappa Patti", unit: "gatthar", gattharSize: 10, currentPrice: 1000, priceHistory: [{ price: 1000, date: "2026-02-13" }] },
    { id: "F057", flowerCat: "Specialty", name: "Pyaz Flower", unit: "bundle", gattharSize: null, currentPrice: 60, priceHistory: [{ price: 60, date: "2026-02-23" }] },
    { id: "F058", flowerCat: "Specialty", name: "Tomato Pattavar", unit: "piece", gattharSize: null, currentPrice: 6, priceHistory: [{ price: 6, date: "2026-02-13" }] },
    { id: "F059", flowerCat: "Specialty", name: "Sitara (Star)", unit: "dozen", gattharSize: null, currentPrice: 150, priceHistory: [{ price: 150, date: "2026-02-13" }] },
    { id: "F060", flowerCat: "Specialty", name: "Kiance", unit: "kg", gattharSize: null, currentPrice: 500, priceHistory: [{ price: 500, date: "2026-02-23" }] },
    { id: "F061", flowerCat: "Specialty", name: "Juppi", unit: "piece", gattharSize: null, currentPrice: 30, priceHistory: [{ price: 30, date: "2026-02-23" }] },
    { id: "F062", flowerCat: "Specialty", name: "Muraya (Murraya)", unit: "gatthar", gattharSize: null, currentPrice: 1000, priceHistory: [{ price: 1000, date: "2026-02-23" }] },
    { id: "F063", flowerCat: "Specialty", name: "Anar (Pomegranate)", unit: "kg", gattharSize: null, currentPrice: 200, priceHistory: [{ price: 200, date: "2026-02-13" }] },
    { id: "F064", flowerCat: "Specialty", name: "Nimbu (Lemon)", unit: "kg", gattharSize: null, currentPrice: 200, priceHistory: [{ price: 200, date: "2026-02-13" }] },
    { id: "F065", flowerCat: "Specialty", name: "Morning Strip", unit: "bundle", gattharSize: null, currentPrice: 150, priceHistory: [{ price: 150, date: "2026-02-13" }] },
    { id: "F066", flowerCat: "Filler & Green", name: "Ferns", unit: "piece", gattharSize: null, currentPrice: 50, priceHistory: [{ price: 50, date: "2026-02-23" }] },
    { id: "F067", flowerCat: "Palm & Leaf", name: "Cactus Palm", unit: "piece", gattharSize: null, currentPrice: 250, priceHistory: [{ price: 250, date: "2026-02-19" }] },
  ],
  synonymDictionary: [
    { id: "SYN1", words: ["Flower", "Floral", "Phool"] },
    { id: "SYN2", words: ["Arch", "Gate", "Entrance", "Dwar"] },
    { id: "SYN3", words: ["Mandap", "Stage", "Platform", "Manch"] },
    { id: "SYN4", words: ["Sofa", "Couch", "Settee"] },
    { id: "SYN5", words: ["Light", "Lamp", "Chandelier", "Jhumar"] },
    { id: "SYN6", words: ["Curtain", "Drape", "Parda"] },
    { id: "SYN7", words: ["Carpet", "Rug", "Dari"] },
    { id: "SYN8", words: ["Table", "Counter", "Desk"] },
    { id: "SYN9", words: ["Backdrop", "Background", "Panel"] },
    { id: "SYN10", words: ["Pillar", "Column", "Khamba"] },
    { id: "SYN11", words: ["Pot", "Vase", "Gamla"] },
    { id: "SYN12", words: ["Marigold", "Genda", "Gainda"] },
    { id: "SYN13", words: ["Rose", "Gulab"] },
    { id: "SYN14", words: ["Jasmine", "Mogra", "Chameli"] },
    { id: "SYN15", words: ["Tuberose", "Rajnigandha"] },
    { id: "SYN16", words: ["Chair", "Kursi", "Seat"] },
    { id: "SYN17", words: ["Ceiling", "Top", "Chaddar"] },
    { id: "SYN18", words: ["Hanging", "Latkane", "Suspension"] },
    { id: "SYN19", words: ["Fabric", "Cloth", "Kapda"] },
    { id: "SYN20", words: ["Frame", "Structure", "Dhaancha"] },
  ],
};

// Seed price-intelligence data shown in the Purchase "Log Purchase" modal.
export const PRICE_HISTORY = {
  "Foam Flower Base": [
    { vendorId: "V001", vendorName: "Raju Flowers", mobile: "9876500001", price: 72, qty: 50, unit: "Piece", date: "2026-03-10" },
    { vendorId: "V002", vendorName: "Kumar Traders", mobile: "9876500002", price: 85, qty: 30, unit: "Piece", date: "2025-12-05" },
    { vendorId: "V003", vendorName: "Delhi Florals", mobile: "9876500003", price: 95, qty: 20, unit: "Piece", date: "2025-10-20" },
  ],
  "Marigold Garland": [
    { vendorId: "V003", vendorName: "Delhi Florals", mobile: "9876500003", price: 45, qty: 80, unit: "Metre", date: "2025-11-15" },
    { vendorId: "V002", vendorName: "Kumar Traders", mobile: "9876500002", price: 52, qty: 50, unit: "Metre", date: "2025-09-10" },
  ],
};
